* 概要
Flaskを中心に、SQLAlchemy、テンプレートエンジンにmakoを使用しています。
Python 2.7を想定しています。
SQLAlchemyは0.8.xに対応したつもり。

* サンプルアプリケーション
python manage.py set_testdata
でテスト用のデータを、
python manage.py run
でテスト用サーバが起動します。
http://localhost:5000/
を開くとリンクの一覧が表示されます。
これを表示しているのは
myojin.myojin.views.top.index()
になります。

* ディレクトリ構成
myojin/
  manage.py      # コマンド実行スクリプト
  static/        # 静的ファイル   デフォルトのURLは例えばhttp://hoge/static/hello.txt
  templates/     # テンプレートファイル
  translations/  # 言語ファイル
  myojin/        # 本体
    base.cfg
    test.base.cfg
    USERNAME.cfg
    core/          # flaskアプリ、データベース、テンプレートエンジン関係の生成、初期化など
      app.py         # flaskアプリ生成
      database.py    # SQLAlchemyのエンジン初期化
      decorators.py  # ログイン必須などのdecorator
      globals.py     # ここで__all__に追加したものがmyojin/myojin/__init__.pyにてmyojinモジュール名前空間に導入される
      initlogging.py # ログ機能の初期化
      mako.py        # テンプレートエンジンに使用しているmakoの初期化
      middlewares.py # wsgiミドルウェアなど。今はメンテナンス画面表示用ミドルウェアのみ。
    apps/          # アプリケーション本体
      main/          # サンプルアプリケーション 
        models/        # モデル定義
          tables/        # テーブル定義
          mappers/       # マッパー定義
          classes/       # クラス定義
	  base.py        # モデルクラスの基底クラス 
        views/         # ビュー
          top.py       # 
	  
* 依存モジュール
rumalchemy
httpagentparser
ipy
SQLAlchemy 0.8.x
flask
flask-script
flask-sqlalchemy
flask-wtf
beaker
mako
tw.rum

* 機能別
** 設定ファイル
実行にはデフォルトで、
user名.cfg
が使用されます。
見つからなければdev.cfgが使用されます。
テスト実行時はusername.test.cfgやtest.cfg
が使用されます。
基本的には、Flask
** コマンド
python manage.py {COMMAND}
で該当コマンドが実行されます。
python manage.py {COMMAND} -c hoge.cfg
で指定した設定ファイルhoge.cfgが使用されます。
*** run(runserver) テストサーバの起動
*** shell (テスト用シェル)
*** test (テストの実行)
*** set_testdata (テスト用データのセット。一度全テーブルを削除してから再作成します。)
set_testdataの中身は、 myojin/myojin/scripts/set_testdata.py内のmain関数です。
同様に、myojin/myojin/scripts以下にdef main():.. を持つhoge.pyを追加すれば
python manage.py hoge
でhoge.mainが実行されます。

** アプリケーションの追加
mainと同様にmyojin/myojin/apps/以下にサブパッケージを作る。
myojin/myojin/apps/hoge/__init__.py
に、
from flaskext.submodule import Module
module = Module(__name__, url_prefix="/hoge")
を追加。これでこのアプリケーションのURLは、/hoge...になる。
myojin/myojin/__init__.pyの
from .apps import main;app.register_module(main.module)
と同等の行を追加。

** モデル
myojin/myojin/apps/main/models
以下にテーブル、モデルクラス、マッパー定義を置きます。
Model.query_allはすべて、
Model.queryは、deleted==False、
Model.userquery は、deleted==False and user==current_user
の条件でfilterしたクエリーを戻します。
設定ファイルは、
SQLALCHEMY_DATABASE_URI = 'sqlite:///dev.db'
の項を設定してください。
その他機能などは、SQLAlchemy, Flask-SQLAlchemyに準じます。
encoded_idで難読化したidを取得できます。難読化だけで暗号ではありません。
Model.decode_idで復号化できます。

** ビュー,コントローラ
*** 追加
main/__init__.py
from . import views;views.top.module.register_to(module)
との行と同様に追加
module = Module(__name__, url_prefix="/hoge")
views.top.module = submodule.SubModule(__name__, url_prefix="/fuga")
views.top.module.register_to(module)
views.top.module.route('/')(f)
で/hoge/fuga/
にマッチします。

*** decorator
**** @module.route('/login', methods=["GET"])
Flaskの@app.routeに準じます
**** @module.templated(templatename)
makoのテンプレートを出力します。
**** @login_required()
ログインしていない場合、リダイレクトします。
*** 認証
Userクラスのクラスメソッドauthenticateからuserインスタンスを取得します。
user = User.authenticate(email=email,password=password)
取得したuserのチェックをしてから、loginメソッドを実行するとログインされます。
user.login()

*** セッション
beakerを使用しています。
configファイルのBEAKER_SETTINGSの項目が
そのままbeaker sessionの初期化に使用されます。
*** URL routing
Flask,werkzeugに準じます。
@module.route('/user/<User:user>')
の書式で、モデルのencode_idがマッチするURLの定義になります。
@module.route('/user/id/<User(attr=id):user>')
でUser.idにマッチするURLが、
@module.route('/user/id/<User(tokenkind=user_by_token, minutes=1):user>')
で、有効期限付きでエンコードされたUser.idを内部にもつトークンを生成します。
有効期限が切れた場合は404を戻します。
tokenkindは使用する関数別に名前を設定してください。
サンプルアプリケーションを参考にしてください。

** 国際化
後々書きます
